name: Release (ZIP on tag)

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install deps & build
        run: |
          composer install --no-dev --prefer-dist --no-interaction
          [ -f package.json ] && npm ci && npm run build || true
      - name: Create ZIP
        run: |
          PLUG=wakilisha-share
          mkdir -p dist
          zip -r "dist/${PLUG}.zip" . -x ".git/*" ".github/*" "node_modules/*" "vendor/bin/*" "tests/*" ".wp-env/*" "playwright-report/*" "test-results/*" "*.map" "*.lock" ".editorconfig" ".gitattributes" ".gitignore" ".DS_Store"
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
